Story4/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/',include('story1.urls')),
    path('story5/',include('story5.urls')),
    path('story6/',include('story6.urls')),
    path('Story7/',include('Story7.urls')),
    path('Story8/',include('Story8.urls')),
    path('Story9/',include('Story9.urls')),
    path('login/',auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="logout.html"),name='logout'),
]

Story7/urls.py
from django.urls import path

from . import views

app_name = 'Story7'

urlpatterns = [
    path('', views.accord, name='accord'),   
]

Story8/urls.py
from django.urls import path

from . import views

app_name = 'Story8'

urlpatterns = [
    path('', views.books, name='books'),
    path('buku/', views.buku, name='buku'),   
]

Story9/urls.py
from django.urls import path

from . import views

app_name = 'Story9'

urlpatterns = [
	path('home/',views.home,name='home'),
	path('', views.signup, name='signup'), 
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('mystory',views.mystory,name='mystory')
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.productbuat, name='productbuat'),
    path('detail/<int:qid>/',views.detail, name='detail'),
    path('hapus/<int:qid>/',views.hapus, name='hapus'),   
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.daftarkegiatan, name='daftarkegiatan'),
    path('anggota/<int:qid>/',views.tambahanggota, name='tambahanggota'),
    path('kegiatan/',views.buatkegiatan, name='buatkegiatan'),   
]

Story7/models.py
from django.db import models

# Create your models here.

Story8/models.py
from django.db import models

# Create your models here.

Story9/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

Story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

class CreateUserForm(UserCreationForm):
	"""docstring for CreateUserForm"""
	class Meta:
		model = User
		fields = {'username','password1','password2'}
		

story5/forms.py
from django import forms

from .models import matkul

class matkulform(forms.ModelForm):
	class Meta:
		model = matkul

		fields =[
			'MataKuliah',
			'Dosen',
			'SKS',
			'Semester',
		]
		help_texts = {
			'MataKuliah' : None,
		}

		labels = {
			'MataKuliah' : 'Mata Kuliah',
			'Dosen'		 :'Nama Dosen'
		}

		widgets = {
			'MataKuliah' : forms.TextInput(attrs={'placeholder': 'Tulis Nama Mata Kuliah','class':'form-control'}),
			'Dosen' : forms.TextInput(attrs={'placeholder': 'Tulis Nama Dosen','class':'form-control'}),
			'SKS' : forms.TextInput( attrs={'placeholder': 'Tulis Jumlah SKS (Angka)','class':'form-control'}),
			'Semester' : forms.TextInput(attrs={'placeholder': 'Contoh: Gasal 2019/2020','class':'form-control'}),
		}

story6/forms.py
from django import forms

from .models import kegiatan, anggota

class kegiatanform(forms.ModelForm):
	class Meta:
		model = kegiatan

		fields =[
			'Judul',
			'Deskripsi',
		]

		widgets = {
			'Judul'    	 : forms.TextInput(attrs={'placeholder': 'Tulis Judul Kegiatan','class':'form-control'}),
			'Deskripsi'  : forms.TextInput(attrs={'placeholder': 'Tulis Deskripsi','class':'form-control'}),
		}

class anggotaform(forms.ModelForm):
	class Meta:
		model = anggota
		exclude = ('kegiatan',)
		fields =[
			'NamaAnggota',
		]

		help_texts = {
			'NamaAnggota' : None,
		}

		labels = {
			'NamaAnggota' : 'Nama Anggota',
		}

		widgets = {
			'NamaAnggota' : forms.TextInput(attrs={'placeholder': 'Tulis Nama Anda','class':'form-control'}),
		}

Story7/views.py
from django.shortcuts import render,redirect

# Create your views here.

def accord(request):
	return render(request,'accord.html')

Story8/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import urllib
import requests
import json
# Create your views here.

def books(request):
	return render(request,'books.html')

def buku(request):
	tmp = "https://www.googleapis.com/books/v1/volumes?q="+request.GET['q']
	bentar = requests.get(tmp)
	data = json.loads(bentar.content)
	return JsonResponse(data,safe=False)

Story9/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
# Create your views here.
def signup(request):
	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			return redirect('Story9:home')
			
	else:
		form = CreateUserForm()
		
	return render(request,'signup.html', {
		'form': form
	});

def home(request):
	return render(request,'home.html')

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def mystory(request):
	return render(request, 'main/mystory.html')

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1.html')

story5/views.py
from django.shortcuts import render,redirect

from .forms import matkulform

from .models import matkul
# Create your views here.

def productbuat(request):
	if request.method == "POST":
		form = matkulform(request.POST)
		if form.is_valid():
			simpan = form.save()
			simpan.save()
	else:
		form = matkulform()

	matkulkeluar = matkul.objects.all()
	context = {
		'form' : form,
		'matkulkeluar':matkulkeluar,
	}
	return render(request,'nyimpen.html',context)

def detail(request,qid):
 	context ={'matkul': matkul.objects.get(id=qid)}    
 	return render (request,'detail.html',context)

def hapus(request,qid):
 	matkul.objects.get(id=qid).delete()
 	return redirect ('story5:productbuat')

story6/views.py
from django.shortcuts import render,redirect

from .forms import kegiatanform, anggotaform

from .models import kegiatan, anggota
# Create your views here.

def buatkegiatan(request):
	if request.method == "POST":
		form = kegiatanform(request.POST)
		if form.is_valid():
			simpan = form.save()	
			simpan.save()
	else:
		form = kegiatanform()

	context = {
		'form' :form,
	}
	return render(request,'buatkegiatan.html',context)

def tambahanggota(request,qid):
	if request.method == "POST":
		form = anggotaform(request.POST)
		if form.is_valid():
			simpan = form.save(commit=False)
			simpan.kegiatan = kegiatan.objects.get(id = qid) 
			simpan.save()
	else:
		form = anggotaform()

	context = {
		'form' :form,
	}
	return render(request,'tambahanggota.html',context)

def daftarkegiatan(request):
	kegiatankeluar = kegiatan.objects.all();
	anggotakeluar  = anggota.objects.all();
	context = {
		'anggotakeluar'	 : anggotakeluar,
		'kegiatankeluar' : kegiatankeluar,
	}
	return render(request,'daftarkegiatan.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'main/static/css/style.css' %}">
  <style>
    /* Project-wide style */

    #nengahcontact{
      text-indent: 80px;
    }

    #nengahemail{
      text-indent: 20px;
    }

    #imgContainer{
        float:left;
        margin: 10px 10px 20px 20px;
    }

    h3 {
        display: inline;
    }

    #kotak{
      width: 350px; 
      float:left; 
      height:200px; 
      margin:10px
    }

    #kotak1{
      width: 550px; 
      float:left; 
      height:200px; 
      margin:10px
    }

    #kotak3{
      width: 220px; 
      float:left; 
      height:200px; 
      margin:10px
    }

    #geser{
      margin-left: 250px;
    }

    body {
      color: #ffffff;
      background-color: #000033;
    }

    img {
        float : left;
        margin-right: 90px;
      background-size:50px 50px;
    }

    .jumbotron{
      color: #ffffff;
      background-color: #000033;
    }


    .center {
      text-align: center;
      border: 100px solid green;
    }
  </style>

  {% block meta %}
  {% endblock meta %}
</head>	

<body style="background-color: #000033;">
   <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/mf-logo_300x.jpg' %}" alt="" width="80" height="40">
           </a>
           <div class="text-center">
                <a class="navbar-brand" id="geser">Michael Felix's Web</a>
            </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story1:story1' %}">Story1</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:home' %}">Story3</a>
            </li>
              <a class="nav-link" href="{% url 'story5:productbuat' %}">Story5</a>
            </li>
            </li>
              <a class="nav-link" href="{% url 'story6:daftarkegiatan' %}">Story6</a>
            </li>
            </li>
              <a class="nav-link" href="{% url 'Story7:accord' %}">Story7</a>
            </li>
            </li>
              <a class="nav-link" href="{% url 'Story8:books' %}">Story8</a>
            </li>
            </li>
              <a class="nav-link" href="{% url 'Story9:home' %}">Story9</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://instagram.com/newbiemaster31">
                <img src="{% static 'img/instagram.png' %}" width="30" height="30" class="rounded-circle" style="margin-right:0px; margin-left:90px;">
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link"href="https://www.facebook.com/profile.php?id=100013777357346">
                <img src="{% static 'img/face.png' %}" width="30" height="30" style="margin-right:0px;margin-top:0px;">
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  {% block content %}
  {% endblock content %}
</body>
</html>