Story4/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/',include('story1.urls')),
    path('story5/',include('story5.urls')),
    path('story6/',include('story6.urls')),
    path('Story7/',include('Story7.urls')),
    path('Story8/',include('Story8.urls')),
    path('Story9/',include('Story9.urls')),
    path('login/',auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="logout.html"),name='logout'),
]

Story7/urls.py
from django.urls import path

from . import views

app_name = 'Story7'

urlpatterns = [
    path('', views.accord, name='accord'),   
]

Story8/urls.py
from django.urls import path

from . import views

app_name = 'Story8'

urlpatterns = [
    path('', views.books, name='books'),
    path('buku/', views.buku, name='buku'),   
]

Story9/urls.py
from django.urls import path

from . import views

app_name = 'Story9'

urlpatterns = [
	path('home/',views.home,name='home'),
	path('', views.signup, name='signup'), 
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('mystory',views.mystory,name='mystory')
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.productbuat, name='productbuat'),
    path('detail/<int:qid>/',views.detail, name='detail'),
    path('hapus/<int:qid>/',views.hapus, name='hapus'),   
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.daftarkegiatan, name='daftarkegiatan'),
    path('anggota/<int:qid>/',views.tambahanggota, name='tambahanggota'),
    path('kegiatan/',views.buatkegiatan, name='buatkegiatan'),   
]

Story7/models.py
from django.db import models

# Create your models here.

Story8/models.py
from django.db import models

# Create your models here.

Story9/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class matkul(models.Model):
	MataKuliah   = models.CharField(max_length = 30, unique=True)
	Dosen        = models.CharField(max_length = 30)
	SKS          = models.IntegerField()
	Semester     = models.CharField(max_length = 30)

	#	return f"/story5/{self.MataKuliah}/"	

story6/models.py
from django.db import models

# Create your models here.

class kegiatan(models.Model):
	Judul	  = models.CharField(max_length = 20)
	Deskripsi = models.CharField(max_length = 100)

class anggota(models.Model):
	NamaAnggota	= models.CharField(max_length=30,unique = True)
	kegiatan    = models.ForeignKey(kegiatan,on_delete=models.CASCADE)

Story9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

class CreateUserForm(UserCreationForm):
	"""docstring for CreateUserForm"""
	class Meta:
		model = User
		fields = {'username','password1','password2'}
		

story5/forms.py
from django import forms

from .models import matkul

class matkulform(forms.ModelForm):
	class Meta:
		model = matkul

		fields =[
			'MataKuliah',
			'Dosen',
			'SKS',
			'Semester',
		]
		help_texts = {
			'MataKuliah' : None,
		}

		labels = {
			'MataKuliah' : 'Mata Kuliah',
			'Dosen'		 :'Nama Dosen'
		}

		widgets = {
			'MataKuliah' : forms.TextInput(attrs={'placeholder': 'Tulis Nama Mata Kuliah','class':'form-control'}),
			'Dosen' : forms.TextInput(attrs={'placeholder': 'Tulis Nama Dosen','class':'form-control'}),
			'SKS' : forms.TextInput( attrs={'placeholder': 'Tulis Jumlah SKS (Angka)','class':'form-control'}),
			'Semester' : forms.TextInput(attrs={'placeholder': 'Contoh: Gasal 2019/2020','class':'form-control'}),
		}

story6/forms.py
from django import forms

from .models import kegiatan, anggota

class kegiatanform(forms.ModelForm):
	class Meta:
		model = kegiatan

		fields =[
			'Judul',
			'Deskripsi',
		]

		widgets = {
			'Judul'    	 : forms.TextInput(attrs={'placeholder': 'Tulis Judul Kegiatan','class':'form-control'}),
			'Deskripsi'  : forms.TextInput(attrs={'placeholder': 'Tulis Deskripsi','class':'form-control'}),
		}

class anggotaform(forms.ModelForm):
	class Meta:
		model = anggota
		exclude = ('kegiatan',)
		fields =[
			'NamaAnggota',
		]

		help_texts = {
			'NamaAnggota' : None,
		}

		labels = {
			'NamaAnggota' : 'Nama Anggota',
		}

		widgets = {
			'NamaAnggota' : forms.TextInput(attrs={'placeholder': 'Tulis Nama Anda','class':'form-control'}),
		}

Story7/views.py
from django.shortcuts import render,redirect

# Create your views here.

def accord(request):
	return render(request,'accord.html')

Story8/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import urllib
import requests
import json
# Create your views here.

def books(request):
	return render(request,'books.html')

def buku(request):
	tmp = "https://www.googleapis.com/books/v1/volumes?q="+request.GET['q']
	bentar = requests.get(tmp)
	data = json.loads(bentar.content)
	return JsonResponse(data,safe=False)

Story9/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
# Create your views here.
def signup(request):
	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			return redirect('Story9:home')
			
	else:
		form = CreateUserForm()
		
	return render(request,'signup.html', {
		'form': form
	});

def home(request):
	return render(request,'home.html')

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def mystory(request):
	return render(request, 'main/mystory.html')

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1.html')

story5/views.py
from django.shortcuts import render,redirect

from .forms import matkulform

from .models import matkul
# Create your views here.

def productbuat(request):
	if request.method == "POST":
		form = matkulform(request.POST)
		if form.is_valid():
			simpan = form.save()
			simpan.save()
	else:
		form = matkulform()

	matkulkeluar = matkul.objects.all()
	context = {
		'form' : form,
		'matkulkeluar':matkulkeluar,
	}
	return render(request,'nyimpen.html',context)

def detail(request,qid):
 	context ={'matkul': matkul.objects.get(id=qid)}    
 	return render (request,'detail.html',context)

def hapus(request,qid):
 	matkul.objects.get(id=qid).delete()
 	return redirect ('story5:productbuat')

story6/views.py
from django.shortcuts import render,redirect

from .forms import kegiatanform, anggotaform

from .models import kegiatan, anggota
# Create your views here.

def buatkegiatan(request):
	if request.method == "POST":
		form = kegiatanform(request.POST)
		if form.is_valid():
			simpan = form.save()	
			simpan.save()
	else:
		form = kegiatanform()

	context = {
		'form' :form,
	}
	return render(request,'buatkegiatan.html',context)

def tambahanggota(request,qid):
	if request.method == "POST":
		form = anggotaform(request.POST)
		if form.is_valid():
			simpan = form.save(commit=False)
			simpan.kegiatan = kegiatan.objects.get(id = qid) 
			simpan.save()
	else:
		form = anggotaform()

	context = {
		'form' :form,
	}
	return render(request,'tambahanggota.html',context)

def daftarkegiatan(request):
	kegiatankeluar = kegiatan.objects.all();
	anggotakeluar  = anggota.objects.all();
	context = {
		'anggotakeluar'	 : anggotakeluar,
		'kegiatankeluar' : kegiatankeluar,
	}
	return render(request,'daftarkegiatan.html',context)

Story7/templates/accord.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 7</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
jQuery(document).ready(function($) {
  $(".judul").click(function() {
    $(this).parent().parent().find('.isi').slideToggle('slow');
  });
 $(".down").click(function(){
  	var tmp = this.parentNode.parentNode.parentNode;
  	console.log(tmp);
  	if(tmp.nextElementSibling)
    	tmp.parentNode.insertBefore(tmp.nextElementSibling,tmp);
  });
 $(".up").click(function(){
  	var tmp=this.parentNode.parentNode.parentNode;
  	console.log(tmp.previousElementSibling);
  	if(tmp.previousElementSibling){
    	tmp.parentNode.insertBefore(tmp,tmp.previousElementSibling);
  	}
  });
});
</script>
<style> 
      .isi {
	    display: none;
	    padding:10px;
	    border-style: solid;
  		border-width: 1px;
  		border-color: white;
  		width: 50%;
	  }
	  .atas {
    		cursor: pointer;
	   		width: 50%;
	      	color: white;
	      	border-radius: 25px;
  			background-color: black;
	      	padding: 10px;
	      	border-radius: 5px;
	      	border: 1px solid grey;
		}


</style>
{% endblock meta %}

{% block content %}
<br><br><br>

<h2 style="text-align: center;">Michael Felix Haryono's Fact</h2>

<br>
<div style="margin-left: 500px;">
	<div id="tempat1">
		<div>
			<div class="atas">
				<h3 class="judul" style="padding-right: 300px;">Aktivitas</h3>
				<button class="up">/\</button>
				<button class="down">\/</button>
			</div>
			<div class="isi">
				<ul>
					<li><h5>Kuliah</h5></li>
					<li><h5>Asisten</h5></li>
					<li><h5>Main game</h5></li>
				</ul>
			</div>
		</div>
	</div>
	<div id="tempat2">
		<div>
			<div class="atas">
				<h3 class="judul" style="padding-right: 110px;">Pengalaman Organisasi</h3>
				<button class="up">/\</button>
				<button class="down">\/</button>
			</div>
			<div class="isi">
				<ul>
					<li><h5>Sesi DekDok</h5></li>
					<li><h5>Asistens PSD</h5></li>
					<li><h5>Bendahara GKI Bobotsari</h5></li>
				</ul>
			</div>
		</div>
	</div>
	<div id="tempat3">
		<div>
			<div class="atas">
				<h3 class="judul" style="padding-right: 310px;">Prestasi</h3>
				<button class="up">/\</button>
				<button class="down">\/</button>
			</div>
			<div class="isi">
				<ul>
					<li><h5>Finalis ICPC</h5></li>
					<li><h5>Peserta OSP Komputer</h5></li>
				</ul>
			</div>
		</div>
	</div>
	<div id="tempat4">
		<div>
			<div class="atas">
				<h3 class="judul" style="padding-right: 345px;">Hobi</h3>
				<button class="up">/\</button>
				<button class="down">\/</button>
			</div>
			<div class="isi">
				<ul>
					<li><h5>Nonton Running Man</h5></li>
					<li><h5>Genshin Impact</h5></li>
					<li><h5>Spacing Out</h5></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<p id="demo"></p>

{% endblock content %}
				

Story8/templates/books.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 7</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<style type="text/css">
table, th, td {
  	border: 1px solid white;
}
</style>
{% endblock meta %}

{% block content %}
<br><br><br>
<div style="text-align: center;">
	<h2>Pencarian Buku</h2>
	<input id="keyword" placeholder="Ketik disini

	">
	<button onclick="search()">search</button>
	<br><br>
	<table id="daftarisi" style="margin-left: auto;margin-right: auto;">
	</table> 
	<p id="demo"></p>
	<script type="text/javascript">
		if($.trim($("#daftarisi").html())=='') {
			var x = myFunction();
			function myFunction() {
			$.ajax({
				url: '/Story8/buku?q=Harry',
				success: function(data){
					console.log(data.content)
					var bookshelf = data.items;
					$("#daftarisi").empty();
					$("#daftarisi").append("<tr><th>Judul</th><th>Gambar</th></tr>");
					for(a=0;a<10;a++){
						var judul = bookshelf[a].volumeInfo.title;
						var gambar= bookshelf[a].volumeInfo.imageLinks.smallThumbnail;
						$("#daftarisi").append("<tr><td>"+judul+"</td><td><img src="+gambar+"><td></tr>");
					}
				}
			});
			}
		}
		function search() {
			var ketikan = $("#keyword");
			console.log(ketikan.val());
			$.ajax({
				url: '/Story8/buku?q='+ketikan.val(),
				success: function(data){
					console.log(data.content)
					var bookshelf = data.items;
					$("#daftarisi").empty();
					$("#daftarisi").append("<tr><th>Judul</th><th>Gambar</th></tr>");
					for(a=0;a<10;a++){
						var judul = bookshelf[a].volumeInfo.title;
						var gambar= bookshelf[a].volumeInfo.imageLinks.smallThumbnail;
						$("#daftarisi").append("<tr><td>"+judul+"</td><td><img src="+gambar+"><td></tr>");
					}
				}
			});
		};
	</script>
</div>
{% endblock content %}
				

Story9/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
<style type="text/css">
	a{
		color:white;
	}
</style>
{% endblock meta %}

{% block content %}
<br><br><br>
{% if user.is_authenticated%}
	<a href="{% url 'logout' %}" style="margin-left: 130px;">Log Out</a>
	<br><br>
	<div style="text-align: center;">
		<h3> Selamat datang {{ user.username }}</h3>
{% else %}
	<a href="{% url 'Story9:signup' %}" style="margin-left: 130px;">Sign Up/</a>
	<a href="{% url 'login' %}">Log In</a>
	<br><br>
	<div style="text-align: center;">
		<h3>Selamat datang</h3>
{% endif %}
</div>
{% endblock content %}
				

Story9/templates/login.html
		{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<div style="margin-left: 550px;">
<h5 style="padding-left: 100px;">Log In</h5>
<br>
<form method="post" class="from-group">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit" style="margin-left:100px;">Log In</button>
</form>
<br>
<div style="padding-left: 40px;">
		<h5> Belum punya akun?</h5>
		<a href="{% url 'Story9:signup' %}">Tekan disini (Sign Up)</a>
	</div>
</div>
{% endblock content %}
				

Story9/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}
<br><br><br><br><br>
<div style="text-align: center;">
	<h3>Anda sudah log out</h3>
	<div style="padding-left: 40px;">
		<a href="{% url 'Story9:home' %}">Kembali ke Home</a>
	</div>
</div>
{% endblock content %}
				

Story9/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}
<br><br><br><br><br>
<div style="margin-left: 550px;">
	<h4 style="padding-left: 120px;">Sign Up</h4>
	<br>
	<form method="post">
		{% csrf_token %}
		<table>
		<tr>
			<td>{{form.username.label}}</td>
			<td>{{form.username}}</td>
		</tr>
		<tr>
			<td>{{form.password1.label}}</td>
			<td>{{form.password1}}</td>
		</tr>
		<tr>
			<td>{{form.password2.label}}</td>
			<td>{{form.password2}}</td>
		</tr>
		</table>
		{{form.errors}}
		<br>
		<div style="padding-left: 150px;">
			<button type="submit">Sign up</button>
		</div>
	</form>
	<br>
	<div style="padding-left: 100px;">
		<h5> Sudah punya akun?</h5>
		<a href="{% url 'login' %}">Tekan disini (login)</a>
	</div>
</div>
{% endblock content %}
				

story1/templates/story1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 1</title>
<style>
        h3 {
            color: brown;
            font-family: verdana;
        }   

        img {
            float : left;
            margin-right: 20px;
            background-size:50px 50px;
        }
        
        body {
            background-color: #ffe6b3;
        }
</style>
{% endblock meta %}

{% block content %}
<br><br><br>    
  <div>
            <div> 
              <h1><center>Profil Saya</center></h1>
                <h3>Data Pribadi</h3>
                <img src="{% static 'img/MichaelFH.jpeg' %}" width="175" height="262">
                <br> <br> 
                <table>
                    <tr>
                        <td>Nama:</td>
                        <td>Michael Felix Haryono</td>
                    </tr>               

                    <tr>
                        <td>NPM:</td>
                        <td>1906398326</td>
                    </tr>

                    <tr>
                        <td>Angkatan:</td>
                        <td>2019</td>
                    </tr>

                    <tr>
            <td>Kuliah:</td>
                        <td>Fasilkom UI</td>
                    </tr>

                    <tr>
                        <td>Hobi:</td>
                        <td>Menonton film</td>
                    </tr>
                </table>
                <h3>Deskripsi</h3>
                <p>Anak yang suka mendengar pendapat-pendapat orang. Suka sekali menonton komedi terutama stand up comedy.</p>
            </div>

            <div >
                <br> 
                <h3>Riwayat Pendidikan</h3>
                <table>
                    <tr>
                        <td>2007-2013</td>
                        <td>SD Pius Purbalingga</td>
                    </tr>

                    <tr>
                        <td>2013-2016</td>
                        <td>SMP Negeri 1 Purbalingga</td>
                    </tr>

                    <tr>
                        <td>2016-2019</td>
                        <td>SMA Negeri 1 Purwokerto</td>
                    </tr>

                    <tr>
                        <td>2019-Sekarang</td>
                        <td>Universitas Indonesia</td>
                    </tr>
                </table>
              <h3>Media Sosial</h3>
              <br>
                    <a  href="https://instagram.com/newbiemaster31"><img src="{%static 'img/instagram.png'%}" width="30" height="30"></a>
            </div>
{% endblock content %}

story5/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 5</title>
<style> 
        body {
            color:#ffffff;
        }
        .form-group {
            background-color: black;  
            border: 3px gray;
            width :500px;
            margin-left:520px; 
        }

        .center{
            background-color: black;  
            width : 0px;
            border: 0px;
            padding-left:170px; 
        }
</style>
{% endblock meta %}
<style>
</style>
{% block content %}
<br><br><br><br>
<h1 style="margin-left: 450px;">Detail dari Mata Kuliah</h1>
<div class="form-group" style="background-color:#000033;">
    <table>
        <tr>
            <td><h2>Mata Kuliah:</h2></td>
            <td><h2>{{ matkul.MataKuliah }}</h2></td>
        </tr>
        <tr>
            <td><h2>Nama Dosen:</h2></td>
            <td><h2>{{ matkul.Dosen }}</h2></td>
        </tr>
        <tr>
            <td><h2>Jumlah SKS:</h2></td>
            <td><h2>{{ matkul.SKS }}</h2></td>
        </tr>
        <tr>
            <td><h2>Semester:</h2></td>
            <td><h2>{{ matkul.Semester }}</h2></td>
        </tr>
    </table>
</div>
<div style="margin-left: 550px;">
    <input type='submit' onclick="location.href='{% url 'TestPengetahuan:ganti' %}'" class="btn btn-secondary btn-lg" value='Previous Page'/>
</div>
{% endblock content %}

story5/templates/nyimpen.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 5</title>
<style> 
        body {
            color:#ffffff;
        }
        .form-group {
            background-color: black;  
            border: 3px gray;
            width :400px;
            margin-left:450px; 
        }

        .center{
            background-color: black;  
            width : 0px;
            border: 0px;
            padding-left:170px; 
        }
</style>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<div action="#" class="form-group">
    <form action="{% url 'story1:story1' %}" method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div action= "#"class="center">
        <input type='submit' class="btn btn-secondary btn-lg" value='Save'/>

    </div>
    </form>
    {% if matkulkeluar %}
        {% for keluar in matkulkeluar %}
        <table>
        <tr>
            <td>
                <h3><a href="{% url 'story5:detail' qid=keluar.id %}">      {{ keluar.MataKuliah }}</a></h3>
            </td>
            <td>
                <input type='submit' onclick="location.href='{% url 'story5:hapus' qid=keluar.id %}'" class="btn btn-secondary btn-sm"value='Hapus'/>
            </td>
        </tr>  
        </table>  
        {% endfor %}
    {% endif %}
</div>
{% endblock content %}

story6/templates/buatkegiatan.html
<!--{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 5</title>
<style> 
        body {
            color:#ffffff;
        }
        .form-group {
            background-color: black;  
            border: 3px gray;
            width :400px;
            margin-left:450px; 
        }

        .center{
            background-color: black;  
            width : 0px;
            border: 0px;
            padding-left:170px; 
        }
</style>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<div action="buatkegiatan" class="form-group">
    <form method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
        <div action= "buatkegiatan.html"class="center">
            <input type='submit' class="btn btn-secondary btn-lg" value='Save'/>
        </div>
    </form>
    <div style="margin-left: 550px;">
    <input type='submit' onclick="location.href='{% url 'story6:daftarkegiatan' %}'" class="btn btn-secondary btn-lg" value='Previous Page'/>
    </div>
</div>
{% endblock content %}-->
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("button").click(function(){
    $("<span>Hello world!</span>").insertAfter("p");
  });
});
</script>
</head>
<body>

<button>Insert span element after each p element</button>

<p>This is a paragraph.</p>
<p>This is another paragraph.</p>

</body>
</html>

story6/templates/daftarkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 6</title>
<style> 
        body {
            color:#ffffff;
        }
        .form-group {
            background-color: black;  
            border: 3px gray;
            width :500px;
            margin-left:520px; 
        }

        .hitam{
            background-color: black;
            padding-left: 80px;  
            width: 300px;
        }
        .center{
            background-color: black;  
            width : 0px;
            border: 0px;
            padding-left:170px; 
        }
</style>
{% endblock meta %}
<style>
</style>
{% block content %}
<br><br><br><br>
<h1 style="margin-left: 520px;">Daftar Kegiatan</h1>
<div class="form-group" style="background-color:#000033;">
    <br><br>
    {% for kegiatan in kegiatankeluar %}
    <div class="hitam">
        <table>
            <tr>
                <h3> {{ kegiatan.Judul }}</h3>
            </tr>
            {% for anggota in anggotakeluar %}
                {% if anggota.kegiatan.Judul == kegiatan.Judul%}
                <tr>
                    <h5 style="margin-left: 40px "> {{ anggota.NamaAnggota }} </h5>
                </tr>
                {% endif %}
            {% endfor%}
            <br>
            <input type='submit' style="margin-left: 20px "onclick="location.href='{% url 'story6:tambahanggota' qid=kegiatan.id %}'" class="btn btn-secondary btn-lg" value='Daftar'/>
            </table>
        </div>  
        <br><br>
    {% endfor %}
    <input type='submit' style="margin-left:40px" onclick="location.href='{% url 'story6:buatkegiatan' %}'" class="btn btn-secondary btn-lg" value='Buat Kegiatan Baru'/>
</div>
{% endblock content %}

story6/templates/tambahanggota.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 6</title>
<style> 
        body {
            color:#ffffff;
        }
        .form-group {
            background-color: black;  
            border: 3px gray;
            width :400px;
            margin-left:450px; 
        }

        .center{
            background-color: black;  
            width : 0px;
            border: 0px;
            padding-left:170px; 
        }
</style>
{% endblock meta %}

{% block content %}
<br><br><br><br>
<div action="tambahanggota" class="form-group">
    <form method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div action= "tambahanggota.html"class="center">
        <input type='submit' class="btn btn-secondary btn-lg" value='Save'/>

    </div>
    </form>
    <div style="margin-left: 550px;">
    <input type='submit' onclick="location.href='{% url 'story6:daftarkegiatan' %}'" class="btn btn-secondary btn-lg" value='Previous Page'/>
    </div>
</div>
{% endblock content %}